# ############################################################################
# Security 
# ############################################################################
  - platform: template
    sensors:
    
      security:
        friendly_name: Security mode
        value_template: "{{ is_state('input_boolean.security_mode', 'on') }}"
        icon_template: >
          {% if is_state('input_boolean.security_mode', 'on') %}
            mdi:shield
          {% elif is_state('input_boolean.security_mode', 'off') %}
            mdi:shield-off
          {% endif %}
      
      motion_internal:
        friendly_name: Motion Internal
        value_template: "{{ is_state('group.motioninternal','on') }}"
        device_class: motion

      motion:
        friendly_name: Motion
        value_template: "{{ is_state('group.motion','on') }}"
        device_class: motion

      motion_unifi:
        friendly_name: Motion Unifi
        value_template: "{{ is_state('group.motionunifi','on') }}"
        device_class: motion

      doors:
        friendly_name: Doors
        value_template: "{{ is_state('group.doors','on') }}"
        device_class: door

      windows:
        friendly_name: Windows
        value_template: "{{ is_state('group.windows','on') }}"
        device_class: window
