substitutions:
  board_name: esp32_poe_ble_hs
  node_name: esp32-poe-ble-hs
  up_int: 60s
  
esphome:
  name: ${node_name}
  comment: "ESP32 POE BLE Gateway HS"
  friendly_name: "ESP32 POE BLE HS"
  area: "Hall Small"   
  # project:
  #   name: esphome.bluetooth-proxy
  #   version: "1.0"
  # platformio_options:
  #   board_build.partitions: ../../../custom_components/partitions_esp32_4mb.csv
  # on_boot:
  #   then:
  #     - output.turn_on: power_led

safe_mode:
  disabled: False
  num_attempts: 5
  reboot_timeout: 15min

external_components:
  - source: github://myhomeiot/esphome-components  

# dashboard_import:
#   package_import_url: github://esphome/bluetooth-proxies/gl-s10.yaml@main

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

ethernet:
  type: IP101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO5

logger:
  baud_rate: 0

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

globals:
  - id: event_count
    type: unsigned int
    restore_value: no
    initial_value: '0'

i2c:
  sda: GPIO15
  scl: GPIO13
  scan: true

esp32_ble_tracker:
  scan_parameters:
    #interval: 1100ms
    #window: 1100ms
    active: true
  # on_ble_advertise:
  #   then:
  #     - if:
  #         condition:
  #           lambda: |-
  #             static const std::vector<esp32_ble_tracker::ESPBTUUID> uuids = {
  #               esp32_ble_tracker::ESPBTUUID::from_raw("00000000-0000-0000-0000-000000000000"),
  #               esp32_ble_tracker::ESPBTUUID::from_raw("00112233-4455-6677-8899-AABBCCDDEEFF"),
  #               esp32_ble_tracker::ESPBTUUID::from_raw("74278BDA-B644-4520-8F0C-720EAF059935")
  #             };

  #             if (!x.get_ibeacon().has_value())
  #               return false;
  #             auto ibeacon = x.get_ibeacon().value();
  #             auto bt_uuid = ibeacon.get_uuid().as_128bit().get_uuid();
  #             std::reverse(bt_uuid.uuid.uuid128, bt_uuid.uuid.uuid128 + bt_uuid.len);
  #             auto uuid = esp32_ble_tracker::ESPBTUUID::from_uuid (bt_uuid);
  #             bool result = std::find(uuids.begin(), uuids.end(), uuid) != uuids.end();
  #             if (result)
  #               ESP_LOGW("iBeacon", "UUID: %s, major/minor: %u/%u, TX power: %d",
  #                 uuid.to_string().c_str(), ibeacon.get_major(), ibeacon.get_minor(), ibeacon.get_signal_power());
  #             else
  #               ESP_LOGD("iBeacon", "UUID: %s", uuid.to_string().c_str());
  #             return result;
  #         then:
  #           - homeassistant.event:
  #               event: esphome.on_ble_advertise
  #               data:
  #                 packet: !lambda return ble_gateway::BLEGateway::scan_result_to_hci_packet_hex(x.get_scan_result());



ble_gateway:
  id: ${board_name}
  #discovery: true
  on_ble_advertise:
    then:
      - homeassistant.event:
          event: esphome.on_ble_advertise
          data:
            packet: !lambda return packet;
            gateway_id: ${board_name}
      - lambda: |-
          id(event_count) += 1;
  # on_ble_advertise:
  #   then:
  #       - homeassistant.service:
  #           service: ble_monitor.parse_data
  #           data:
  #             packet: !lambda return packet;
  #             gateway_id: ${board_name}
  #       - lambda: |-
  #           id(event_count) += 1;
            
# bluetooth_proxy:
#   active: false

# web_server:
#   port: 80

# status_led:
#   pin:
#     number: GPIO32
#     inverted: true

binary_sensor:
  - platform: status
    name: "Status"
    # on_press:
    #   - output.turn_on: bluetooth_led
    # on_release:
    #   - output.turn_off: bluetooth_led

  # - platform: ble_presence
  #   mac_address: 7E:FE:3E:EC:59:FB
  #   name: "White"
  #   device_class: presence

  # - platform: ble_presence
  #   mac_address: 3B:EF:3E:DE:98:6B
  #   name: "Grey"
  #   device_class: presence

  # - platform: ble_presence
  #   mac_address: 2A:BC:3E:DC:57:65
  #   name: "Pink"
  #   device_class: presence

  # - platform: ble_presence
  #   mac_address: 6B:9C:3E:D1:C5:9A
  #   name: "Green"
  #   device_class: presence

  - platform: gpio
    pin: 
      number: GPIO33
      inverted: true
    name: "Reset Button"
    use_interrupt: true


output:
  - platform: gpio
    pin: GPIO14
    inverted: true
    id: power_led
    
  - platform: gpio
    pin: GPIO12
    inverted: true
    id: bluetooth_led

  - platform: gpio
    pin: GPIO32
    inverted: true
    id: status_led

sensor:
  - platform: uptime
    name: "Uptime s"
    id: uptime_sensor
    update_interval: 15s
    #disabled_by_default: true
    
  - platform: template
    name: "Events"
    lambda: |-
      return id(event_count);
    update_interval: ${up_int}
    icon: mdi:cube-send
    unit_of_measurement: 'event'
    accuracy_decimals: 0

text_sensor:
  - platform: template
    name: "Uptime"
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

  - platform: homeassistant
    id: ble_gateway_devices
    entity_id: binary_sensor.ble_gateway
    attribute: devices
    on_value:
      then:
        - lambda: id(${board_name}).set_devices(x);

  - platform: ethernet_info
    ip_address:
      name: "IP"

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    
button:
  - platform: restart
    name: "Restart"

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow

interval:
  - interval: ${up_int}
    then:
      - lambda: |-
          static bool flag = false;
          auto min = id(sntp_time).now().minute;
          if (min == 59 && !flag)
          {
            id(event_count) = 0;
            flag = true;
          }
          else
          {
            flag = false;
          }